spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        use_sql_comments: true

  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: https://withtail.duckdns.org/api/oauth2/callback/google

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: ${ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}
  refresh-token-validity-in-milliseconds: ${REFRESH_TOKEN_VALIDITY_IN_MILLISECONDS}

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: myawswithtail
    region:
      static: ap-northeast-2
    stack:
      auto: false

coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET}
    domain: ${COOLSMS_DOMAIN}
    from: ${COOLSMS_FROM}